name: php linting

on:
  push:
    paths:
      - '**.php'

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Pint
        uses: aglipanci/laravel-pint-action@latest
        with:
          pintVersion: 1.22.1

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
