name: Compile release build

on:
  release:
    types: [released]
    
jobs:
  prepare_next_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@main

      - name: Update version number in plugin
        uses: mingjun97/file-regex-replace@v1
        with:
          include: 'teecontrol\.php'
          flags: 'g'
          regex: 'Version: ([0-9\.]*)'
          replacement: 'Version: ${{ steps.get_next_version.outputs.version }}'

      - name: Update version number in package.json
        uses: mingjun97/file-regex-replace@v1
        with:
          include: 'package\.json'
          flags: 'g'
          regex: '"version": "([0-9\.]*)",'
          replacement: '"version": "${{ steps.get_next_version.outputs.version }}",'

      - name: Update version number in readme
        uses: mingjun97/file-regex-replace@v1
        with:
          include: 'readme\.txt'
          flags: 'g'
          regex: 'Stable tag: ([0-9\.]*)'
          replacement: 'Stable tag: ${{ steps.get_next_version.outputs.version }}'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update version number
          branch: main

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup composer
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-dev"

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile build
        run: npm run build

      - name: Zip plugin
        run: npm run plugin-zip

      - name: Upload zip
        uses: softprops/action-gh-release@v2
        with:
          files: 'teecontrol.zip'
