name: Update version

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update version number
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: teecontrol.php
          find: "^(Version: [0-9]*\.[0-9]*\.[0-9]*)$"
          replace: Version: ${{ github.event.release.tag_name }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update version number
